title: "Desafio Anzan & Soroban Tools"
description: "Ferramentas e técnicas de cálculo mental, Flash Anzan e Abaco."
baseurl: "/desafio-anzan-blog" 
url: "https://mauriciomendes-gif.github.io" 

remote_theme: pages-themes/minima@master
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
